### ISSUE TITLE
为什么要有数据转换，直接文件读取进去不能使用么？

### ISSUE THREAD

**Issue by cyqluowang** [fengzhongyouxia/Tensorflow#2]
https://github.com/fengzhongyouxia/Tensorflow/blob/master/tf_spark/TensorflowOnSpark2/%E5%8E%9F%E7%89%88/mnist_data_setup2.py

普通的处理好的0，1，2特征这样的文件
sc.textFile(args.tracks)

**Comment by cyqluowang** [comment]
18/03/24 00:21:07 WARN TaskSetManager: Lost task 1.0 in stage 5.0 (TID 11, bi-dev-05, executor 1): org.apache.spark.SparkException: Can only zip RDDs with same number of elements in each partition
	at org.apache.spark.rdd.RDD$$anonfun$zip$1$$anonfun$apply$27$$anon$2.hasNext(RDD.scala:859)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.rdd.RDD$$anonfun$zip$1$$anonfun$apply$27$$anon$2.foreach(RDD.scala:855)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:328)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
